Capstone Project week 3 - Part 2

I will copy-paste all the code run in the part1 before of moving on

In [10]:
import pandas as pd

url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

read_table = pd.read_html(url,header=[0])

df = read_table[0]

df = df[df.Borough !='Not assigned']

df.reset_index(drop=True,inplace=True)

df_grouped = df.groupby('Postal Code',as_index=False).agg(lambda x: ','.join(set(x.dropna())))

df_grouped.loc[df_grouped['Neighbourhood'] == 'Not assigned','Neighbourhood'] = df_grouped['Borough']

df_grouped.shape[0]

  Postal Code      Borough                           Neighbourhood
0         M1B  Scarborough                          Malvern, Rouge
1         M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2         M1E  Scarborough       Guildwood, Morningside, West Hill
3         M1G  Scarborough                                  Woburn
4         M1H  Scarborough                               Cedarbrae

Now I will continue with the second part..

In [7]:
# Read the  csv file that has the geographical coordinates of each postal code

df_codes = pd.read_csv('http://cocl.us/Geospatial_data')
df_codes.head()
df_codes.shape[0] # to check that we have the same number than the previous table

103

In [12]:
# We need to cross the two tables

df_cross = pd.merge(left=df_grouped,right=df_codes,on='Postal Code')
df_cross.head()

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476